language: cpp

sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq -y
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -K $encrypted_357164081e8e_key -iv $encrypted_357164081e8e_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

install:
  - sudo apt-get -y --no-install-recommends install latexmk texlive-latex3 texlive-latex-recommended texlive-latex-extra texlive-fonts-extra pgf cmake octave octave-odepkg gnuplot

script:
  - mkdir build && cd build && cmake .. && make -j32
  - ssh-keyscan -H r2labs.us > ~/.ssh/known_hosts
  - scp homeworks/hw*/hw+([0-9]).pdf static@r2labs.us:/srv/http/static/m374m/
  - scp notes/notes.pdf static@r2labs.us:/srv/http/static/m374m/
  - scp exams/*/*.pdf static@r2labs.us:/srv/http/static/m374m/
